### ISSUE TITLE
Don't camel case routes

### ISSUE THREAD

**Issue by AmanRaj1608** [iiitv/alumni-portal#8]
https://stackoverflow.com/a/18450653/11097431

Change this `url/MeetTheAlumni` to `url/meet-the-alumni`

This `url/aboutus` to `url/about-us`

**Comment by nlok5923** [comment]
Thanks @AmanRaj1608 sir for opening this issue [this](https://github.com/iiitv/alumni-portal/commit/f1e2ea643af2edcd732eb14fbb7f3da9f505bb27)  commit resolves this issue
